# Generated by Django 5.2.1 on 2025-06-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="hr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hr_name", models.CharField(max_length=20)),
                ("hr_email", models.CharField(max_length=30)),
            ],
        ),
    ]
